apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prod-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.11.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: simplel2
  namespace: metallb-system
