# Helmsman

helmRepos:
  kafka-ui: https://provectus.github.io/kafka-ui-charts

namespaces:
  default:
  metallb-system:

apps:
  metallb:
    namespace: metallb-system
    enabled: true
    wait: true
    chart: oci://registry-1.docker.io/bitnamicharts/metallb
    version: 6.1.3
    valuesFile: metallb.yml
    priority: -4

  kafka:
    namespace: default
    enabled: true
    wait: true
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: 28.1.1
    priority: -3
    set:
      controller.replicaCount: 1
      controller.livenessProbe.initialDelaySeconds: 120
      provisioning.numPartitions: 2
      extraConfig: |
        offsets.topic.replication.factor=1
        transaction.state.log.replication.factor=1
        log.retention.hours=24
        log.retention.bytes=2147483648

  # To enable: helm install kafka-ui kafka-ui/kafka-ui -f kafka-ui.yml --version 0.7.6
  kafka-ui:
    namespace: default
    enabled: false
    chart: kafka-ui/kafka-ui
    version: 0.7.6
    priority: -2
    valuesFile: kafka-ui.yml

  payload-processor:
    namespace: default
    enabled: true
    chart: payload-processor
    version: 0.1.0
    priority: -1
    set:
      image.tag: "payload-processor-$COMMIT_SHA"

  rest-api:
    namespace: default
    enabled: true
    chart: rest-api
    version: 0.1.0
    priority: -1
    set:
      image.tag: "rest-api-$COMMIT_SHA"
