# Default values for payload-processor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# NOTE: This string "@@//src/payload-processor/cmd:push" needs to be present
# in order to limtations of the helm_rules bazel package

replicaCount: 1

db:
  password: "{DB_PASSWORD}"

image:
  repository: docker.io/baitinq/fs-tracer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{IMAGE_TAG}"
