apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-api.fullname" . }}
  labels:
    {{- include "rest-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9999
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "rest-api.selectorLabels" . | nindent 4 }}
